Algoritmo "ExMatriz"

Var

   linha , coluna: inteiro
   nome : vetor [1..3,1..3] de caracter

Inicio
   para linha de 1 ate 3 passo 1 faca
      para coluna de 1 ate 3 passo 1 faca
         escreval("digite seu nome :")
         leia (nome[linha,coluna])
      fimpara
   fimpara
   para linha de 1 ate 3 passo 1 faca
      para coluna de 1 ate 3 passo 1 faca
         escreva (nome[linha,coluna], "")
      fimpara
      escreval("")
   fimpara

Fimalgoritmo